wine = read.csv('winemag-data_first150k.csv', stringsAsFactors = F)
library(dplyr)
wine = wine %>% select(-description)
wine$country = ifelse(wine$designation == 'Askitikos', 'Greece', wine$country)
wine$country = ifelse(wine$designation == 'Piedra Feliz', 'Chile', wine$country)
selected_countries = wine %>% group_by(country) %>% summarise(count=n()) %>% arrange(desc(count)) %>% top_n(10) %>% select(country)
selected_countries = as.character(selected_countries$country)
library(shiny)
wine$variety = ifelse(wine$variety == "Bordeaux-style Red Blend", "Red Blend", wine$variety)